config/routes.rb
Rails.application.routes.draw do
  resources :cards

  resources :phrases

  root 'cards#index'

  get 'generate' => 'phrases#generate'

end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :card_phrases
  has_many :phrases, through: :card_phrases
end

app/models/card_phrase.rb
class CardPhrase < ActiveRecord::Base
  belongs_to :card
  belongs_to :phrase
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  has_many :card_phrases
  has_many :cards, through: :card_phrases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.phrases = Phrase.order("RANDOM()").limit(25)
    respond_to do |format|
      if @card.save
        format.html { redirect_to @card }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params[:card]
    end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  # before_action :set_phrase, only: [:show, :edit, :update, :destroy]

  # GET /phrases
  # GET /phrases.json
  def index
    @phrases = Phrase.all
  end

  # GET /phrases/1
  # GET /phrases/1.json

  def generate
    @phrases = Phrase.all
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
  end

  # GET /phrases/1/edit
  def edit
  end

  # POST /phrases
  # POST /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: 'Phrase was successfully created.' }
        format.json { render action: 'show', status: :created, location: @phrase }
      else
        format.html { render action: 'new' }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1
  # PATCH/PUT /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to @phrase, notice: 'Phrase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase.destroy
    respond_to do |format|
      format.html { redirect_to phrases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phrase_params
      params[:phrase]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="heading">
  <h1 class="title">Soccer Bingo</h1>
  <%= button_to "Generate Bingo Card", cards_path %>
</div>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div class="container">
      <div class="game-container">
        <div class="grid-container">
          <div class="grid-row">
            <div class="grid-cell">
              <div class="bingo">B</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">I</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">N</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">G</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">O</div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="center-tile"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
</table>

<br>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div class="container">
      <div class="game-container">
        <div class="grid-container">
          <div class="grid-row">
            <div class="grid-cell">
              <div class="bingo">B</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">I</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">N</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">G</div>
            </div>
            <div class="grid-cell">
              <div class="bingo">O</div>
            </div>
          </div>

          <% @card.phrases.each_slice(5) do |row| %>
            <div class="grid-row">
              <% row.each do |phrase| %>
                <div class="grid-cell">
                  <div class="line">
                    <a href="" data-background-color="#009900" data-text-color="#FFFFFF"><%= phrase.line %></a>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

</table>

<br>

<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soccer Bingo!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phrases/_form.html.erb
<%= form_for(@phrase) do |f| %>
  <% if @phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% @phrase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<h1>Generate Bingo Card</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= button_to "Some Button", :action=> "cards_path" %>
    <div class="container">
      <div class="game-container">
        <div class="grid-container">
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase">BINGO</div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
          <div class="grid-row">
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
            <div class="grid-cell">
              <div class="phrase"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <% @phrases.each do |phrase| %>
      <tr>
        <td><%= phrase.line %></td>
        <td><%= link_to 'Show', phrase %></td>
        <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
        <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>